# Generated by Django 6.0.2 on 2026-03-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
