# Generated by Django 6.0.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
