# Generated by Django 6.0.2 on 2026-03-10 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_comments_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('has_used', models.BooleanField(default=False)),
                ('task_type', models.CharField(choices=[('activate_account', 'Activate Account'), ('reset_password', 'Reset Password')], max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
